// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "qr-io.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message DataContentBlob
 */
export interface DataContentBlob {
    /**
     * @generated from protobuf oneof: content
     */
    content: {
        oneofKind: "textContent";
        /**
         * @generated from protobuf field: string text_content = 1
         */
        textContent: string;
    } | {
        oneofKind: "bytesContent";
        /**
         * @generated from protobuf field: bytes bytes_content = 2
         */
        bytesContent: Uint8Array;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: int32 content_length = 10
     */
    contentLength: number;
}
/**
 * @generated from protobuf message DataTransferBlob
 */
export interface DataTransferBlob {
    /**
     * @generated from protobuf oneof: content
     */
    content: {
        oneofKind: "textContent";
        /**
         * @generated from protobuf field: string text_content = 1
         */
        textContent: string;
    } | {
        oneofKind: "bytesContent";
        /**
         * @generated from protobuf field: bytes bytes_content = 2
         */
        bytesContent: Uint8Array; // string bytes_base64_content = 3;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message FinalDataContentId
 */
export interface FinalDataContentId {
    /**
     * @generated from protobuf field: string final_content_hash_b64 = 1
     */
    finalContentHashB64: string;
    /**
     * @generated from protobuf field: ContentHashAlgorithm content_hash_algorithm = 2
     */
    contentHashAlgorithm: ContentHashAlgorithm;
    /**
     * @generated from protobuf field: int32 final_content_bytes_size = 3
     */
    finalContentBytesSize: number;
}
/**
 * @generated from protobuf message DataTxDetails
 */
export interface DataTxDetails {
    /**
     * @generated from protobuf field: float expected_tx_frame_rate = 1
     */
    expectedTxFrameRate: number;
    /**
     * @generated from protobuf field: int32 expected_bytes_per_frame = 2
     */
    expectedBytesPerFrame: number;
    /**
     * @generated from protobuf field: int32 expected_frame_count = 3
     */
    expectedFrameCount: number;
}
/**
 * @generated from protobuf message QrDataFrameContentId
 */
export interface QrDataFrameContentId {
    /**
     * @generated from protobuf field: string tx_stream_id = 1
     */
    txStreamId: string;
    /**
     * @generated from protobuf field: int32 this_content_index = 2
     */
    thisContentIndex: number;
}
/**
 * @generated from protobuf message QrTxStreamMetadata
 */
export interface QrTxStreamMetadata {
    /**
     * @generated from protobuf field: string tx_stream_id = 1
     */
    txStreamId: string;
    /**
     * @generated from protobuf field: int32 expected_total_frame_count = 2
     */
    expectedTotalFrameCount: number;
    /**
     * @generated from protobuf field: int32 expected_bytes_per_frame = 3
     */
    expectedBytesPerFrame: number; // ContentDataTransferType frame_encoding = 3;
    /**
     * @generated from protobuf field: string content_name = 4
     */
    contentName: string;
    /**
     * @generated from protobuf field: string content_mime_type = 5
     */
    contentMimeType: string;
    /**
     * @generated from protobuf field: FinalDataContentId final_data_content_id = 6
     */
    finalDataContentId?: FinalDataContentId; // float expected_tx_frames_per_second = 6;
}
/**
 * @generated from protobuf message QrContentFrameTxData
 */
export interface QrContentFrameTxData {
    /**
     * @generated from protobuf field: QrDataFrameContentId content_tx_id = 1
     */
    contentTxId?: QrDataFrameContentId;
    /**
     * bytes tx_content_bytes = 2;
     *
     * @generated from protobuf field: DataTransferBlob tx_content = 2
     */
    txContent?: DataTransferBlob;
}
/**
 * @generated from protobuf message QrHeaderFrameData
 */
export interface QrHeaderFrameData {
    /**
     * @generated from protobuf field: QrTxStreamMetadata tx_stream_metadata = 1
     */
    txStreamMetadata?: QrTxStreamMetadata;
    /**
     * @generated from protobuf field: QrContentFrameTxData content_tx_data = 2
     */
    contentTxData?: QrContentFrameTxData;
}
/**
 * @generated from protobuf message QrDataFrame
 */
export interface QrDataFrame {
    /**
     * @generated from protobuf oneof: frame
     */
    frame: {
        oneofKind: "header";
        /**
         * @generated from protobuf field: QrHeaderFrameData header = 1
         */
        header: QrHeaderFrameData;
    } | {
        oneofKind: "contentTx";
        /**
         * @generated from protobuf field: QrContentFrameTxData contentTx = 2
         */
        contentTx: QrContentFrameTxData;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message QrDataFrames
 */
export interface QrDataFrames {
    /**
     * @generated from protobuf field: repeated QrDataFrame frames = 1
     */
    frames: QrDataFrame[];
}
// enum ContentDataTransferType {
//   FRAME_DATA_TYPE_UNSPECIFIED = 0;
//   FRAME_DATA_TYPE_TEXT = 1;
//   FRAME_DATA_TYPE_BYTES = 2;
//   FRAME_DATA_TYPE_BYTES_BASE64 = 3;
// }

// enum DataTransferEncoding {
//   DATA_TRANSFER_ENCODING_UNSPECIFIED = 0;
//   DATA_TRANSFER_ENCODING_TEXT = 1;
//   DATA_TRANSFER_ENCODING_BYTES = 2;
//   DATA_TRANSFER_ENCODING_BYTES_BASE64 = 3;
// }

/**
 * @generated from protobuf enum ContentHashAlgorithm
 */
export enum ContentHashAlgorithm {
    /**
     * @generated from protobuf enum value: CONTENT_HASH_ALGORITHM_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: CONTENT_HASH_ALGORITHM_QRIO = 1;
     */
    QRIO = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class DataContentBlob$Type extends MessageType<DataContentBlob> {
    constructor() {
        super("DataContentBlob", [
            { no: 1, name: "text_content", kind: "scalar", oneof: "content", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "bytes_content", kind: "scalar", oneof: "content", T: 12 /*ScalarType.BYTES*/ },
            { no: 10, name: "content_length", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message DataContentBlob
 */
export const DataContentBlob = new DataContentBlob$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataTransferBlob$Type extends MessageType<DataTransferBlob> {
    constructor() {
        super("DataTransferBlob", [
            { no: 1, name: "text_content", kind: "scalar", oneof: "content", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "bytes_content", kind: "scalar", oneof: "content", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message DataTransferBlob
 */
export const DataTransferBlob = new DataTransferBlob$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FinalDataContentId$Type extends MessageType<FinalDataContentId> {
    constructor() {
        super("FinalDataContentId", [
            { no: 1, name: "final_content_hash_b64", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content_hash_algorithm", kind: "enum", T: () => ["ContentHashAlgorithm", ContentHashAlgorithm, "CONTENT_HASH_ALGORITHM_"] },
            { no: 3, name: "final_content_bytes_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message FinalDataContentId
 */
export const FinalDataContentId = new FinalDataContentId$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataTxDetails$Type extends MessageType<DataTxDetails> {
    constructor() {
        super("DataTxDetails", [
            { no: 1, name: "expected_tx_frame_rate", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 2, name: "expected_bytes_per_frame", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "expected_frame_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message DataTxDetails
 */
export const DataTxDetails = new DataTxDetails$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QrDataFrameContentId$Type extends MessageType<QrDataFrameContentId> {
    constructor() {
        super("QrDataFrameContentId", [
            { no: 1, name: "tx_stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "this_content_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message QrDataFrameContentId
 */
export const QrDataFrameContentId = new QrDataFrameContentId$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QrTxStreamMetadata$Type extends MessageType<QrTxStreamMetadata> {
    constructor() {
        super("QrTxStreamMetadata", [
            { no: 1, name: "tx_stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "expected_total_frame_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "expected_bytes_per_frame", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "content_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "content_mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "final_data_content_id", kind: "message", T: () => FinalDataContentId }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message QrTxStreamMetadata
 */
export const QrTxStreamMetadata = new QrTxStreamMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QrContentFrameTxData$Type extends MessageType<QrContentFrameTxData> {
    constructor() {
        super("QrContentFrameTxData", [
            { no: 1, name: "content_tx_id", kind: "message", T: () => QrDataFrameContentId },
            { no: 2, name: "tx_content", kind: "message", T: () => DataTransferBlob }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message QrContentFrameTxData
 */
export const QrContentFrameTxData = new QrContentFrameTxData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QrHeaderFrameData$Type extends MessageType<QrHeaderFrameData> {
    constructor() {
        super("QrHeaderFrameData", [
            { no: 1, name: "tx_stream_metadata", kind: "message", T: () => QrTxStreamMetadata },
            { no: 2, name: "content_tx_data", kind: "message", T: () => QrContentFrameTxData }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message QrHeaderFrameData
 */
export const QrHeaderFrameData = new QrHeaderFrameData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QrDataFrame$Type extends MessageType<QrDataFrame> {
    constructor() {
        super("QrDataFrame", [
            { no: 1, name: "header", kind: "message", oneof: "frame", T: () => QrHeaderFrameData },
            { no: 2, name: "contentTx", kind: "message", oneof: "frame", T: () => QrContentFrameTxData }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message QrDataFrame
 */
export const QrDataFrame = new QrDataFrame$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QrDataFrames$Type extends MessageType<QrDataFrames> {
    constructor() {
        super("QrDataFrames", [
            { no: 1, name: "frames", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => QrDataFrame }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message QrDataFrames
 */
export const QrDataFrames = new QrDataFrames$Type();
